// metadata/root.ts
//
// Site-wide keywords + default metadata, applied in app/layout.tsx. Every
// route inherits these fields and overrides only what differs (see the
// per-route files). `homeKeywords` is also the list any route inherits when it
// doesn't define its own.

import type { Metadata } from "next";

import { siteConfig } from "@/config/site";

export const homeKeywords: string[] = [
  // Personal identifiers
  "Gurlivleen",
  "Kainth",
  "Gurlivleen Singh",
  "Gurlivleen Singh Kainth",
  "Gurlivleen Kainth Portfolio",
  "Gurlivleen Developer",
  "Gurlivleen Software Engineer",
  "Gurlivleen Melbourne",

  // Core roles and professional titles
  "Developer",
  "Engineer",
  "Software",
  "Software Developer",
  "Software Engineer",
  "Full Stack",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Web Developer",
  "Mobile Developer",
  "Cross Platform Developer",
  "App Developer",
  "Technical Lead",
  "Team Lead",
  "Agile Developer",
  "Freelancer",
  "Remote Developer",
  "Programmer",

  // Primary technologies and frameworks
  "Next",
  "Next.js",
  "React",
  "React.js",
  "Angular",
  "Flutter",
  "TypeScript",
  "JavaScript",
  "Python",
  "Go",
  "Golang",
  "Java",
  "Spring",
  "Spring Boot",
  "Node",
  "Node.js",
  "Express",
  "Express.js",
  "HTML",
  "CSS",
  "SCSS",
  "Sass",

  // Databases, backend, cloud, CI/CD
  "Firebase",
  "Firestore",
  "Google Cloud",
  "GCP",
  "Google Cloud Functions",
  "MongoDB",
  "MySQL",
  "SQL",
  "Database",
  "Backend",
  "CI/CD",
  "Docker",
  "Jenkins",
  "Serverless",
  "Serverless Architecture",
  "REST",
  "REST API",
  "Microservices",

  // Tools & development practices
  "Git",
  "GitHub",
  "GitLab",
  "Agile",
  "Scrum",
  "DevOps",
  "DevOps Pipeline",
  "Continuous Integration",
  "Continuous Deployment",
  "Version Control",
  "Jira",
  "Testing",
  "Automation",
  "Performance",

  // Domain-specific & project-based
  "SaaS",
  "SaaS Developer",
  "Parking",
  "Parking Management",
  "Parking Management System",
  "POS",
  "POS Integration",
  "Therapy",
  "Online Therapy",
  "Healthcare",
  "Healthcare Tech",
  "CRM",
  "CMS",
  "Dashboard",
  "Real-time",
  "Real-time Dashboard",
  "Cloud",
  "Cloud Apps",

  // Skills and soft skills
  "Leadership",
  "Mentorship",
  "Project",
  "Project Management",
  "Client Management",
  "Communication",
  "Problem Solving",
  "Critical Thinking",
  "Collaboration",
  "Teamwork",
  "Adaptability",
  "Continuous Learning",
  "Efficiency",

  // Education & location
  "Swinburne",
  "Swinburne University",
  "Swinburne University of Technology",
  "Guru Nanak Dev Engineering College",
  "GNDEC",
  "Melbourne",
  "Victoria",
  "Australia",

  // SEO + industry relevance
  "Portfolio",
  "Website",
  "Web Development",
  "Web",
  "Frontend",
  "Backend",
  "UI",
  "UX",
  "Design",
  "Responsive",
  "Interface",
  "User Experience",
  "Modern Web",
  "App Development",
  "Mobile",
  "Cloud Development",
  "Software Architecture",
  "Scalable",
  "Scalable Systems",
  "Enterprise Software",
  "Solutions",
  "Innovation",
  "Technology",
  "Coding",
  "Programming",
  "Development",
  "Tech",
  "Engineer Portfolio",
  "Software Portfolio",
];

export const rootMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  applicationName: siteConfig.name,
  authors: [{ name: siteConfig.author, url: siteConfig.url }],
  creator: siteConfig.author,
  publisher: siteConfig.author,
  keywords: homeKeywords,
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  openGraph: {
    type: "website",
    url: siteConfig.url,
    title: `${siteConfig.name} | Software Developer Portfolio`,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: `${siteConfig.url}/og-home.jpg`,
        width: 1200,
        height: 630,
        alt: "Portfolio banner showing Gurlivleen Singh Kainth's software development projects",
      },
    ],
    locale: "en_AU",
  },
  twitter: {
    card: "summary_large_image",
    site: siteConfig.twitterHandle,
    creator: siteConfig.twitterHandle,
    title: `${siteConfig.name} | Software Developer Portfolio`,
    description: siteConfig.description,
    images: [`${siteConfig.url}/og-home.jpg`],
  },
  alternates: {
    canonical: siteConfig.url,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  // No `verification` field: gurlivleen.dev is verified in Google Search
  // Console as a Domain property via a DNS TXT record, so a meta tag is
  // redundant.
  category: "Software Development",
  classification: "Professional Portfolio",
};
